ALTER TABLE "Genres" ADD COLUMN "osearchName" character varying(32);

UPDATE "Genres" SET "osearchName" = 'film action'                     WHERE "_id" = 1   ;
UPDATE "Genres" SET "osearchName" = 'film animation'                  WHERE "_id" = 2   ;
UPDATE "Genres" SET "osearchName" = 'film aventure'                   WHERE "_id" = 3   ;
UPDATE "Genres" SET "osearchName" = 'émission'                        WHERE "_id" = 4   ;
UPDATE "Genres" SET "osearchName" = 'classique'                       WHERE "_id" = 5   ;
UPDATE "Genres" SET "osearchName" = 'comédie'                         WHERE "_id" = 6   ;
UPDATE "Genres" SET "osearchName" = 'comédie dramatique'              WHERE "_id" = 7   ;
UPDATE "Genres" SET "osearchName" = 'comédie'                         WHERE "_id" = 8   ;
UPDATE "Genres" SET "osearchName" = 'concert'                         WHERE "_id" = 9   ;
UPDATE "Genres" SET "osearchName" = 'film jeunesse'                   WHERE "_id" = 10  ;
UPDATE "Genres" SET "osearchName" = 'autre'                           WHERE "_id" = 11  ;
UPDATE "Genres" SET "osearchName" = 'documentaire'                    WHERE "_id" = 12  ;
UPDATE "Genres" SET "osearchName" = 'drame'                           WHERE "_id" = 13  ;
UPDATE "Genres" SET "osearchName" = 'film horreur'                    WHERE "_id" = 14  ;
UPDATE "Genres" SET "osearchName" = 'film action'                     WHERE "_id" = 15  ;
UPDATE "Genres" SET "osearchName" = 'contemporain'                    WHERE "_id" = 16  ;
UPDATE "Genres" SET "osearchName" = 'film TV comédie'                 WHERE "_id" = 17  ;
UPDATE "Genres" SET "osearchName" = 'film fantastique/SF'             WHERE "_id" = 18  ;
UPDATE "Genres" SET "osearchName" = 'film de guerre'                  WHERE "_id" = 19  ;
UPDATE "Genres" SET "osearchName" = 'doc. histoire'                   WHERE "_id" = 20  ;
UPDATE "Genres" SET "osearchName" = 'film horreur'                    WHERE "_id" = 21  ;
UPDATE "Genres" SET "osearchName" = 'film jeunesse'                   WHERE "_id" = 22  ;
UPDATE "Genres" SET "osearchName" = 'film suspense'                   WHERE "_id" = 23  ;
UPDATE "Genres" SET "osearchName" = 'autre'                           WHERE "_id" = 24  ;
UPDATE "Genres" SET "osearchName" = 'court-métrage'                   WHERE "_id" = 25  ;
UPDATE "Genres" SET "osearchName" = 'comédie musicale'                WHERE "_id" = 26  ;
UPDATE "Genres" SET "osearchName" = 'film TV'                         WHERE "_id" = 27  ;
UPDATE "Genres" SET "osearchName" = 'film TV'                         WHERE "_id" = 28  ;
UPDATE "Genres" SET "osearchName" = 'film TV comédie romantique'      WHERE "_id" = 29  ;
UPDATE "Genres" SET "osearchName" = 'film fantastique/SF'             WHERE "_id" = 30  ;
UPDATE "Genres" SET "osearchName" = 'doc. sports'                     WHERE "_id" = 31  ;
UPDATE "Genres" SET "osearchName" = 'événement sports'                WHERE "_id" = 32  ;
UPDATE "Genres" SET "osearchName" = 'film suspense'                   WHERE "_id" = 33  ;
UPDATE "Genres" SET "osearchName" = 'film suspense'                   WHERE "_id" = 34  ;
UPDATE "Genres" SET "osearchName" = 'film TV'                         WHERE "_id" = 35  ;
UPDATE "Genres" SET "osearchName" = 'western'                         WHERE "_id" = 36  ;